---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/books":
    post:
      summary: Create a Book
      tags:
      - Books
      parameters: []
      responses:
        '200':
          description: Book created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                edition:
                  type: integer
                publication_year:
                  type: string
                authors:
                  type: string
              required:
              - name
              - edition
              - publication_year
              - authors
    get:
      summary: Retrives Books
      tags:
      - Books
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Books retrived
          content: {}
  "/v1/books/{id}":
    get:
      summary: Retrives a Book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Book retrived
          content: {}
    patch:
      summary: Updates a Book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Book is updated
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                edition:
                  type: integer
                publication_year:
                  type: string
                authors:
                  type: string
    delete:
      summary: deletes a Book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Book deleted
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
